[workspace]
members = ["crates/app-core"]
resolver = "2"

[package]
name = "tauri-template"
version = "0.1.0"
description = "Minimal Tauri 2 application template"
authors = ["moritzbrantner"]
edition = "2021"

[lib]
name = "tauri_template_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
app-core = { path = "crates/app-core" }
tauri = { version = "2", features = [] }
